hoe("specialchars ěščřžýáíéůúďťüň")
hoe("showfps")

AddFile("data_old/intro.hx")

Wait(0.1)
Fade("ff000000", 0.2)
LoadImage("picture vary con:'test'")
Fade("00000000", 0.2)
SetText("titulky","Město vzkvétalo")
Wait(2)

Fade("ffffffff", 0.2)
LoadImage("picture vary1 con:'test'")
Fade("00000000", 0.2)
SetText("titulky","Město vzkvétalo, ale já si oproti té honosné fasádě")
Wait(2)

Fade("ffffffff", 0.2)
LoadImage("picture vary-2 con:'test'")
Fade("00000000", 0.2)
SetText("titulky","Já si oproti té honosné fasádě připadal jak v propadlišti")
Wait(2)

Fade("ff000000", 0.2)
LoadImage("picture na_pivu con:'test'")
Fade("00000000", 0.2)
SetText("titulky","Lidé bohatli, ale zahodili svoje štěstí a šlapali po něm")
Wait(3)

Fade("ff000000", 0.2)
Fade("00000000", 0.2)
LoadImage("picture TMA con:'test'")
SetText("titulky","Vlastně jako já")
Wait(2)

LoadImage("picture drunken con:'test'")
SetText("titulky", "Čím více měli, tím více pili, aby neviděli prázdnotu svých životů")
Wait(3)

Fade("ff000000", 0.1)
SetText("titulky","Vlastně jako já2")
Wait(1)
Fade("00000000", 0.1)

LoadImage("picture TMA con:'test'")
SetText("Můj děda byl jiný, neskrýval svůj smutek jako oni")
Wait(3)
SetText("titulky","On se celý život pachtil se svým receptem")
Wait(3)
SetText("titulky","Věřil v jeho dobrý vliv")
Wait(3)
SetText("titulky","Vždy uvařil sotva pro sebe a své přátele")
Wait(3)

LoadImage("picture drunken con:'test'")
SetText("titulky","Lidé se mu jen vysmívali, člověku ze starých dob")
Wait(3)

SetText("Báli se ho, jelikož  s nimi nespadl prázdnoty")
Wait(3)

Fade("ff000000", 0.1)
SetText("titulky","Vlastně jako já")
Wait(1)
Fade("00000000", 0.1)

Wait(0.1)
LoadImage("picture biti con:'test'")
SetText("titulky","Museli je zničit")
Wait(2)

Fade("ff000000", 1)
LoadImage("picture postel con:'test'")
Fade("00000000", 3)
Wait(1.4)
Fade("ffffffff", 0.3)
Fade("00000000", 0.3)
SetText("titulky","Myslel sem, že se tam zavírá se svým žalem, nikdy sem za ním nechodil.")
Wait(3)
